export const topicData = {
    "gas": 89,
    "oil": 403,
    "consumption": 4,
    "market": 19,
    "gdp": 7,
    "war": 2,
    "production": 35,
    "export": 38,
    "battery": 1,
    "": 93,
    "biofuel": 4,
    "policy": 7,
    "economy": 20,
    "strategy": 1,
    "robot": 3,
    "growth": 51,
    "economic": 2,
    "energy": 43,
    "food": 5,
    "administration": 2,
    "unemployment": 3,
    "trade": 3,
    "demand": 4,
    "economic growth": 9,
    "industry": 3,
    "capital": 2,
    "worker": 2,
    "tension": 1,
    "terrorism": 1,
    "transport": 3,
    "peak oil": 1,
    "vehicle": 5,
    "tourist": 1,
    "artificial intelligence": 1,
    "climate": 2,
    "power": 11,
    "crisis": 2,
    "ice": 2,
    "population": 4,
    "politics": 1,
    "business": 4,
    "work": 1,
    "coal": 6,
    "gamification": 1,
    "finance": 1,
    "interest rate": 2,
    "risk": 2,
    "inflation": 1,
    "asylum": 1,
    "resource": 1,
    "plastic": 1,
    "electricity": 2,
    "bank": 4,
    "gasoline": 4,
    "car": 6,
    "money": 3,
    "technology": 5,
    "aquaculture": 1,
    "city": 2,
    "investment": 4,
    "revenue": 1,
    "emission": 5,
    "climate change": 2,
    "infrastructure": 2,
    "government": 3,
    "security": 3,
    "software": 1,
    "building": 1,
    "transportation": 2,
    "wealth": 2,
    "clothing": 1,
    "shortage": 1,
    "debt": 4,
    "agriculture": 1,
    "tax": 1,
    "carbon": 1,
    "brexit": 1,
    "workforce": 1,
    "change": 1,
    "automaker": 1,
    "nuclear": 2,
    "3D": 1,
    "water": 3,
    "data": 1,
    "fossil fuel": 1,
    "election": 1,
    "greenhouse gas": 2,
    "information": 2,
    "shale gas": 1,
    "factory": 1,
    "farm": 1,
    "communication": 1,
    "storm": 1,
    "consumer": 1,
    "material": 1,
    "Washington": 1,
    "pollution": 1,
    "fracking": 1
  };